### ISSUE TITLE
Not Working with Firefox in kali linux offline

### ISSUE THREAD

**Issue by stevanuscolonne** [x0a/thumbdata3-viewer#2] opened 2019-02-12 08:28 UTC
Only show 4 grey boxes area without any image but works firefox in windows 7
Supposed to show 1106 thumbnail images as show below
![screenshot from 2019-02-12 15-27-01](https://user-images.githubusercontent.com/24591481/52621797-c129c880-2eda-11e9-8829-d52085e55219.png)
but actual only show 4 grey boxes
![screenshot from 2019-02-12 15-23-40](https://user-images.githubusercontent.com/24591481/52621649-76a84c00-2eda-11e9-8224-c980074cffec.png)

**Comment by x0a** [comment] 2019-02-12 09:36
Thanks for the report.
A couple of questions to help me troubleshoot this.

1. Can you press F12 (open Web Console) and post a screenshot of any logged errors?
2. Which version of Firefox?
3. Does the "online" version work in the same browser: https://x0a.github.io/thumbdata3-viewer/
If it detects the same number of images on Chrome/Windows as Firefox/Kali, but then fails to display them, it means the parser is working but maybe the underlying data (the file) is changing before the images can be displayed? 

I don't have Kali Linux but I have Ubuntu and am unable to replicate on Firefox 63.0

**Comment by x0a** [comment] 2019-02-19 02:04
I have been able to replicate the bug with Kali Linux 2019.1 using Firefox 60 ESR. Problem was Firefox was incorrectly assuming blob URLs from worker.js were cross origin and refusing to load them. This appears to be an unreported Firefox bug.

Fixed in https://github.com/x0a/thumbdata3-viewer/commit/796a63a750631287466d6e18ee87153963b687cb by having worker.js send raw binary data instead of blob URLs, and having index.js create the object URLs instead

Please try the new version and verify that the problem is resolved. Feel free to reopen this issue if you are still having problems

Thanks

**Closed as completed by x0a** 2019-02-19 02:04 UTC
Labels: bug
